<?php

namespace Database\Seeders\Nepal;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;
use RuntimeException;

class NepalBranchAssignmentSeeder extends Seeder
{
    private const COVERAGE_TABLE = 'coverage_locations';

    private const ASSIGNMENT_TABLE = 'branch_coverage_assignments';

    public function run(): void
    {
        if (!Schema::hasTable('branches')) {
            throw new RuntimeException(
                'The branches table does not exist.'
            );
        }

        if (!Schema::hasTable(self::COVERAGE_TABLE)) {
            throw new RuntimeException(
                'The coverage_locations table does not exist.'
            );
        }

        $assignmentsCreated = 0;

        $mainAssignments = $this->assignMainBranches();

        $subAssignments = $this->assignSubBranches();

        $assignmentsCreated = $mainAssignments + $subAssignments;

        $this->command?->info(
            'Branch allocation assignments seeded successfully.'
        );

        $this->command?->line(
            "Assignments created or updated: {$assignmentsCreated}"
        );
    }

    private function assignMainBranches(): int
    {
        $count = 0;

        $mainBranches = DB::table('branches')
            ->whereIn('type', [
                'branch',
                'main_branch',
                'franchise_branch',
            ])
            ->where(function ($query) {
                $query
                    ->where('status', 'active')
                    ->orWhere('is_active', true);
            })
            ->orderBy('id')
            ->get();

        foreach ($mainBranches as $branch) {
            $allocation = $this->findAllocationForBranch(
                branchId: $branch->id,
                allocationType: 'main_branch_zone',
                branchCode: $branch->code ?? null,
            );

            if (!$allocation) {
                $this->command?->warn(
                    "Main allocation not found for branch: {$branch->name}"
                );

                continue;
            }

            $this->assign(
                branch: $branch,
                allocation: $allocation,
                assignmentType: 'main_branch',
            );

            $count++;
        }

        return $count;
    }

    private function assignSubBranches(): int
    {
        $count = 0;

        $subBranches = DB::table('branches')
            ->where('type', 'sub_branch')
            ->where(function ($query) {
                $query
                    ->where('status', 'active')
                    ->orWhere('is_active', true);
            })
            ->orderBy('id')
            ->get();

        foreach ($subBranches as $branch) {
            $allocation = $this->findAllocationForBranch(
                branchId: $branch->id,
                allocationType: 'sub_branch_zone',
                branchCode: $branch->code ?? null,
            );

            if (!$allocation) {
                $this->command?->warn(
                    "Sub-branch allocation not found for: {$branch->name}"
                );

                continue;
            }

            $this->assign(
                branch: $branch,
                allocation: $allocation,
                assignmentType: 'sub_branch',
            );

            $count++;
        }

        return $count;
    }

    private function findAllocationForBranch(
        int $branchId,
        string $allocationType,
        ?string $branchCode,
    ): ?object {
        /*
         * Preferred lookup when coverage_locations contains branch_id.
         */
        if (Schema::hasColumn(self::COVERAGE_TABLE, 'branch_id')) {
            $allocation = DB::table(self::COVERAGE_TABLE)
                ->where('branch_id', $branchId)
                ->where('type', $allocationType)
                ->first();

            if ($allocation) {
                return $allocation;
            }
        }

        /*
         * Fallback lookup using the allocation code generated by
         * NepalBranchAllocationSeeder.
         */
        if ($branchCode) {
            $prefix = $allocationType === 'main_branch_zone'
                ? 'MAIN'
                : 'SUB';

            $allocationCode = $prefix
                . '-'
                . strtoupper($branchCode)
                . '-ZONE';

            return DB::table(self::COVERAGE_TABLE)
                ->where('code', $allocationCode)
                ->where('type', $allocationType)
                ->first();
        }

        return null;
    }

    private function assign(
        object $branch,
        object $allocation,
        string $assignmentType,
    ): void {
        /*
         * Save directly on branches when the branch table contains
         * coverage_location_id.
         */
        if (Schema::hasColumn('branches', 'coverage_location_id')) {
            $branchUpdate = [
                'coverage_location_id' => $allocation->id,
            ];

            if (Schema::hasColumn('branches', 'updated_at')) {
                $branchUpdate['updated_at'] = now();
            }

            DB::table('branches')
                ->where('id', $branch->id)
                ->update($branchUpdate);
        }

        /*
         * Save in the assignment table when it exists.
         */
        if (!Schema::hasTable(self::ASSIGNMENT_TABLE)) {
            return;
        }

        /*
         * Ensure only one primary active allocation is assigned to
         * a branch at one time.
         */
        $deactivatePayload = $this->filterColumns(
            self::ASSIGNMENT_TABLE,
            [
                'is_primary' => false,
                'status' => 'inactive',
                'is_active' => false,
                'updated_at' => now(),
            ],
        );

        if (!empty($deactivatePayload)) {
            DB::table(self::ASSIGNMENT_TABLE)
                ->where('branch_id', $branch->id)
                ->where('coverage_location_id', '!=', $allocation->id)
                ->update($deactivatePayload);
        }

        $existingAssignment = DB::table(self::ASSIGNMENT_TABLE)
            ->where('branch_id', $branch->id)
            ->where('coverage_location_id', $allocation->id)
            ->first();

        $payload = $this->filterColumns(
            self::ASSIGNMENT_TABLE,
            [
                'branch_id' => $branch->id,
                'coverage_location_id' => $allocation->id,

                'assignment_type' => $assignmentType,

                'is_primary' => true,
                'status' => 'active',
                'is_active' => true,

                'assigned_at' => now(),
                'effective_from' => now()->toDateString(),
                'effective_to' => null,

                'notes' => sprintf(
                    'Automatically assigned %s to %s.',
                    $allocation->name,
                    $branch->name,
                ),

                'created_at' => $existingAssignment?->created_at ?? now(),
                'updated_at' => now(),
            ],
        );

        DB::table(self::ASSIGNMENT_TABLE)->updateOrInsert(
            [
                'branch_id' => $branch->id,
                'coverage_location_id' => $allocation->id,
            ],
            $payload,
        );
    }

    private function filterColumns(string $table, array $data): array
    {
        return collect($data)
            ->filter(
                fn ($value, string $column) =>
                    Schema::hasColumn($table, $column)
            )
            ->toArray();
    }
}